export const jewelry = [
    {
        id: 1,
        name: 'ember',
        description: 'hand chiseled antique japanese teacup piece set in sterling silver',
        price: 60,
        image: 'j.png',
        size: 'small',
        weight: '3 grams',
        stone: 'porcelain',
    },
    {
        id: 2,
        name: 'imelda',
        description: 'hand chiseled antique english teacup piece set in sterling silver',
        price: 60,
        image: 'y.png',
        size: 'small',
        weight: '3 grams',
        stone: 'porcelain',
    },
    {
        id: 3,
        name: 'constantine',
        description: 'turquoise set in sterling silver',
        price: 75,
        image: 't.png',
        size: 'small',
        weight: '8 grams',
        stone: 'turquise',
    },
    {
        id: 4,
        name: 'mary',
        description: 'antique english teacup peice set in silver',
        price: 60,
        image: 'f.png',
        size: 'small',
        weight: '3 grams',
        stone: 'porcelain',
    },
    {
        id: 5,
        name: 'esther',
        description: 'hand chiseled antique english teacup piece set in sterling silver',
        price: 60,
        image: 'p.png',
        size: 'small',
        weight: '3 grams',
        stone: 'porcelain',
    },
    {
        id: 6,
        name: 'dianna',
        description: 'antique english teacup peice set in silver',
        price: 60,
        image: 'e.png',
        size: 'small',
        weight: '3 grams',
        stone: 'turquise',
    }
];