export const jewelry = [
    {
        id: 1,
        name: 'ember',
        description: 'antique teacup piece set in .925 silver, silver chain included',
        price: 60,
        image: 'j.png',
        size: 'small',
        weight: '3 grams',
        stone: 'porcelain',
    },
    {
        id: 2,
        name: 'imelda',
        description: 'antique teacup piece set in .925 silver, silver chain included',
        price: 60,
        image: 'y.png',
        size: 'small',
        weight: '3 grams',
        stone: 'porcelain',
    },
    {
        id: 3,
        name: 'constantine',
        description: 'turquoise set in sterling silver on silver band',
        price: 75,
        image: 't.png',
        size: '7.5',
        weight: '8 grams',
        stone: 'turquise',
    },
    {
        id: 4,
        name: 'mary',
        description: 'antique teacup peice set in .925 silver, silver chain included',
        price: 60,
        image: 'f.png',
        size: 'small',
        weight: '3 grams',
        stone: 'porcelain',
    },
    {
        id: 5,
        name: 'esther',
        description: 'antique teacup piece set in .925 silver, silver chain included',
        price: 60,
        image: 'p.png',
        size: 'small',
        weight: '3 grams',
        stone: 'porcelain',
    },
    {
        id: 6,
        name: 'dianna',
        description: 'antique teacup peice set in .925 silver, silver chain included',
        price: 60,
        image: 'e.png',
        size: 'small',
        weight: '3 grams',
        stone: 'porcelain',
    }
];