export const jewelry = [
    {
        id: 1,
        name: 'ember',
        description: 'hand chiseled antique japanese teacup piece set in sterling silver',
        price: 60,
        image: 'j.png',
        size: 'small',
        weight: '3 grams',
        stone: 'turquise',
    },
    {
        id: 2,
        name: 'imelda',
        description: 'hand chiseled antique english teacup piece set in sterling silver',
        price: 60,
        image: 'y.png',
        size: 'small',
        weight: '3 grams',
        stone: 'turquise',
    },
    {
        id: 3,
        name: 'constantine',
        description: 'turquoise set in sterling silver',
        price: 60,
        image: 'r.png',
        size: 'small',
        weight: '3 grams',
        stone: 'turquise',
    },
    {
        id: 4,
        name: 'ember',
        description: 'hand chiseled antique japanese teacup piece set in sterling silver',
        price: 60,
        image: 'f.png',
        size: 'small',
        weight: '3 grams',
        stone: 'turquise',
    },
    {
        id: 5,
        name: 'imelda',
        description: 'hand chiseled antique english teacup piece set in sterling silver',
        price: 60,
        image: '../assets/',
        size: 'small',
        weight: '3 grams',
        stone: 'turquise',
    },
    {
        id: 6,
        name: 'constantine',
        description: 'turquoise set in sterling silver',
        price: 60,
        image: '../assets/',
        size: 'small',
        weight: '3 grams',
        stone: 'turquise',
    }
];